### PR TITLE
Compile fix: Adds pthread to the libraries that have to be linked.

### PR DESCRIPTION
**Pull request by Rauldg**

### CODE REVIEW

**Comment by doudou** [comment]
CMake has support for the thread init library, could you use this instead ?

~~~
find_package (Threads)
...
target_link_libraries (mytarget ${CMAKE_THREAD_LIBS_INIT})
~~~

**Comment by leifole** [comment]
This whole driver is deprecated, we are using imu_xsens now in nearly all of our projects.

**Comment by Rauldg** [comment]
> This whole driver is deprecated, we are using imu_xsens now in nearly all of our projects.

Is there another driver? Where?

**Comment by Rauldg** [comment]
> CMake has support for the thread init library, could you use this instead ? [...]

Updated

**Comment by doudou** [comment]
> This whole driver is deprecated, we are using imu_xsens now in nearly all of our projects.

Which does not seem to be available on GitHub and in Rock.

**Comment by leifole** [comment]
Because of the underlying proprietary xsens license

Am 21. Juni 2018 17:10:58 MESZ schrieb Sylvain Joyeux <notifications@github.com>:
>> This whole driver is deprecated, we are using imu_xsens now in nearly
>all of our projects.
>
>Which does not seem to be available on GitHub and in Rock.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/rock-drivers/drivers-xsens_imu/pull/1#issuecomment-399138487

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by doudou** [comment]
> Because of the underlying proprietary xsens license

We already had this discussion. One would have to modify the driver's CMake code to look for the SDK in a user-provided place and properly error if it's not provided. Something I personally obviously cannot do, given that I have neither the driver, nor the SDK. As I already said, I'm willing to help.

Regardless. You can't claim this driver is deprecated if there's no alternative for it.

**Pull request merged**
